### ISSUE TITLE
CTUN mode does not add offset on CW Rx

### ISSUE THREAD

**Issue by radi8** [g0orx/pihpsdr#11]
Hello John,

The CTUN mode is one of the best features of the radio when using it for things like contesting etc. as it doesn't change the relative position of signals when tuning around and allows you to keep the spectrum picture in your head.

When clicking on a CW signal the carrier frequency snaps to the click position rather than the centre of the audio passband as it does in normal mode and requires tweaking the frequency for each frequency click.

It is not a high priority as the mode is still very usable. The radio is coming along really well and is now matching most of its big brothers for features you really need and use - I am so impressed.

73, Graeme ZL2APV

**Comment by g0orx** [comment]
I believe this is now fixed.
