### ISSUE TITLE
[Question] GPIO pull-up resistors

### ISSUE THREAD

**Issue by ExplodingLemur** [g0orx/pihpsdr#119]
The schematic shows pull-ups for the Pi and expander GPIOs and the board has footprints for what I assume are pull-up resistors on every pushbutton.  The pull-up resistors aren't called out on the BoM though.  I assume the internal pull-ups on the Pi and expander are being used instead?

**Comment by kc9xg** [comment]
Raspberry PI GPIO pins have internal pullups.
![GPIOSchematic](https://user-images.githubusercontent.com/18682554/84571052-9366c500-ad56-11ea-82b0-119558e77580.PNG)

**Comment by g0orx** [comment]
We added the pull-up resistors as there were some problems with wiringpi
not setting them correctly on the Raspberry Pi 4.

-- John
