### ISSUE TITLE
[RFC] Rig Control

### ISSUE THREAD

**Issue by jaebird** [g0orx/pihpsdr#12]
I'm wondering if the plan for rig control is to use only TS-2000 commands? I'm looking at hamlib and currently the TS-2000 backend only supports Serial port. However, just tweaking it to support Network seems to work with piHPSDR. The reason for the question is that if piHPSDR is going to extend the standard TS-2000 ICD, then it makes sense to name the backend "HPSDR" or something like it.

Thanks,
Jae K5JAE

**Comment by g0orx** [comment]
Thanks to you support Hamlib now supports TCP/IP ;-)
