### ISSUE TITLE
gui freezes when switching receivers with zoom applied

### ISSUE THREAD

**Issue by human-blip** [g0orx/pihpsdr#122]
If 2 receivers are running and zoom is applied to one, switching to the other receiver by clicking on it results in the gui freezing. Sound is heard from the newly selected receiver.  Tested on v2.0.0-rc11 and v2.0.0-rc10.

Switching receivers using the A<>B toolbar button works fine.

**Comment by g0orx** [comment]
Fixed with v2.0.0-rc12 release.
