### ISSUE TITLE
Using a small 4.3" display / Button can't be reached

### ISSUE THREAD

**Issue by dm6tt** [g0orx/pihpsdr#27]
I try to use a BeagleBlack board with a small 4.3" pluged in display.
The display has 480x272 pixel.
The compilation and start went well. The SDR is discovered but I'm not able to press the button, since it is out of the display.
The size is recognized right:
_sysname: Linux
nodename: beaglebone
release: 3.8.13-bone50
version: #1 SMP Tue May 13 13:24:52 UTC 2014
machine: armv7l
width=480 height=272
display_width=480 display_height=272
create top level window._

Regards

73, Marcus, DM6TT

**Comment by g0orx** [comment]
Sorry but the software is designed to work with the RPI 7 inch display
which is 800x480.

If you want to make changes to work with a smaller screen then feel free to
fork the code and make any changes and then submit them for merging.  Just
make sure the changes are conditionally compiled in.

-- John
