### ISSUE TITLE
Problems using Beaglebone Black (with 7" display)

### ISSUE THREAD

**Issue by dm6tt** [g0orx/pihpsdr#30]
Hi folks,
I switched the display of my beaglebone to a 7" (1024x600.)
Compiling the code was no problem, but when I start, I get full_rx_buffer errors and the waterfall / spectrum of the program is not displayed.
The Button/sliders can be seen, but one core is completely busy.

I use a debian system: $ uname -a
Linux beaglebone 3.8.13 #1 SMP Sat Aug 9 11:31:19 CST 2014 armv7l GNU/Linux

The SDR is a redpitaya. This works fine with the same pihpsdr version compiled on x86 and a raspy3.

Here is the console log from the beaglebone:

**Build: 2017-03-10 v1.1.3-beta
sysname: Linux
nodename: beaglebone
release: 3.8.13
version: #1 SMP Sat Aug 9 11:31:19 CST 2014
machine: armv7l
width=2560 height=1024
display_width=800 display_height=480
create top level window
create grid
add grid
create image
add image to grid
create pi label
add pi label to grid
create build label
add build label to grid
create status
add status to grid
init
audio_get_cards
input_device: plughw:0,0 DA830 EVM
output_device: plughw:0,0 DA830 EVM
discovery
old_discovery
discover: looking for HPSDR devices on eth0
discover: bound to eth0
discover_receive_thread
discovered: received 60 bytes
discovery: found device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: bytes read -1
discovery: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
discovery: exiting discover_receive_thread
discover: exiting discover for eth0
discovery found 1 devices
discovery: found device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
new_discover: looking for HPSDR devices on eth0
new_discover: bound to eth0 192.168.10.167 255.255.255.0
new_disovery: thread_id=0x68ec0
new_discover: bytes read -1
new_discover: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
new_discover: exiting new_discover_receive_thread
new_discover: exiting discover for eth0
new_discovery found 1 devices
discovery: found protocol=0 device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: found 1 devices
0x42344 protocol=0 name=Metis
showing device dialog
discovery
old_discovery
discover: looking for HPSDR devices on eth0
discover: bound to eth0
discover_receive_thread
discovered: received 60 bytes
discovery: found device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: bytes read -1
discovery: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
discovery: exiting discover_receive_thread
discover: exiting discover for eth0
discovery found 1 devices
discovery: found device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
new_discover: looking for HPSDR devices on eth0
new_discover: bound to eth0 192.168.10.167 255.255.255.0
new_disovery: thread_id=0x1508f0
new_discover: bytes read -1
new_discover: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
new_discover: exiting new_discover_receive_thread
new_discover: exiting discover for eth0
new_discovery found 1 devices
discovery: found protocol=0 device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: found 1 devices
0x42344 protocol=0 name=Metis
showing device dialog
discovery
old_discovery
discover: looking for HPSDR devices on eth0
discover: bound to eth0
discover_receive_thread
discovered: received 60 bytes
discovery: found device=0 software_version=21 status=2 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: bytes read -1
discovery: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
discovery: exiting discover_receive_thread
discover: exiting discover for eth0
discovery found 1 devices
discovery: found device=0 software_version=21 status=2 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
new_discover: looking for HPSDR devices on eth0
new_discover: bound to eth0 192.168.10.167 255.255.255.0
new_disovery: thread_id=0x150a60
new_discover: bytes read -1
new_discover: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
new_discover: exiting new_discover_receive_thread
new_discover: exiting discover for eth0
new_discovery found 1 devices
discovery: found protocol=0 device=0 software_version=21 status=2 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: found 1 devices
0x42344 protocol=0 name=Metis
showing device dialog
start_cb: 0x42344
start_radio: selected radio=0x42344 device=0
radioRestoreState: 00-26-32-F0-12-D8.props
loadProperties: 00-26-32-F0-12-D8.props
bandRestoreState: restore bands
memRestoreState: restore memory
RESTORE: index=0 title=10
RESTORE MEM:Mem 0=FreqA    28010000
RESTORE: index=0 mode=4
RESTORE: index=0 filter=0
RESTORE: index=1 title=10
RESTORE MEM:Mem 1=FreqA    28010000
RESTORE: index=1 mode=4
RESTORE: index=1 filter=0
RESTORE: index=2 title=10
RESTORE MEM:Mem 2=FreqA    28010000
RESTORE: index=2 mode=4
RESTORE: index=2 filter=0
RESTORE: index=3 title=10
RESTORE MEM:Mem 3=FreqA    28010000
RESTORE: index=3 mode=4
RESTORE: index=3 filter=0
RESTORE: index=4 title=10
RESTORE MEM:Mem 4=FreqA    28010000
RESTORE: index=4 mode=4
RESTORE: index=4 filter=0
radio: vfo_init
vfo_init: width=525 height=60
radio: meter_init
meter_init: width=200 height=60
Create 2 receivers: height=150
create_receiver: id=0 buffer_sizeuild: 2017-03-10 v1.1.3-beta
sysname: Linux
nodename: beaglebone
release: 3.8.13
version: #1 SMP Sat Aug 9 11:31:19 CST 2014
machine: armv7l
width=2560 height=1024
display_width=800 display_height=480
create top level window
create grid
add grid
create image
add image to grid
create pi label
add pi label to grid
create build label
add build label to grid
create status
add status to grid
init
audio_get_cards
input_device: plughw:0,0 DA830 EVM
output_device: plughw:0,0 DA830 EVM
discovery
old_discovery
discover: looking for HPSDR devices on eth0
discover: bound to eth0
discover_receive_thread
discovered: received 60 bytes
discovery: found device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: bytes read -1
discovery: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
discovery: exiting discover_receive_thread
discover: exiting discover for eth0
discovery found 1 devices
discovery: found device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
new_discover: looking for HPSDR devices on eth0
new_discover: bound to eth0 192.168.10.167 255.255.255.0
new_disovery: thread_id=0x68ec0
new_discover: bytes read -1
new_discover: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
new_discover: exiting new_discover_receive_thread
new_discover: exiting discover for eth0
new_discovery found 1 devices
discovery: found protocol=0 device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: found 1 devices
0x42344 protocol=0 name=Metis
showing device dialog
discovery
old_discovery
discover: looking for HPSDR devices on eth0
discover: bound to eth0
discover_receive_thread
discovered: received 60 bytes
discovery: found device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: bytes read -1
discovery: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
discovery: exiting discover_receive_thread
discover: exiting discover for eth0
discovery found 1 devices
discovery: found device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
new_discover: looking for HPSDR devices on eth0
new_discover: bound to eth0 192.168.10.167 255.255.255.0
new_disovery: thread_id=0x1508f0
new_discover: bytes read -1
new_discover: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
new_discover: exiting new_discover_receive_thread
new_discover: exiting discover for eth0
new_discovery found 1 devices
discovery: found protocol=0 device=0 software_version=21 status=3 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: found 1 devices
0x42344 protocol=0 name=Metis
showing device dialog
discovery
old_discovery
discover: looking for HPSDR devices on eth0
discover: bound to eth0
discover_receive_thread
discovered: received 60 bytes
discovery: found device=0 software_version=21 status=2 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: bytes read -1
discovery: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
discovery: exiting discover_receive_thread
discover: exiting discover for eth0
discovery found 1 devices
discovery: found device=0 software_version=21 status=2 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
new_discover: looking for HPSDR devices on eth0
new_discover: bound to eth0 192.168.10.167 255.255.255.0
new_disovery: thread_id=0x150a60
new_discover: bytes read -1
new_discover: recvfrom socket failed for discover_receive_thread: Resource temporarily unavailable
new_discover: exiting new_discover_receive_thread
new_discover: exiting discover for eth0
new_discovery found 1 devices
discovery: found protocol=0 device=0 software_version=21 status=2 address=192.168.10.70 (00:26:32:F0:12:D8) on eth0
discovery: found 1 devices
0x42344 protocol=0 name=Metis
showing device dialog
start_cb: 0x42344
start_radio: selected radio=0x42344 device=0
radioRestoreState: 00-26-32-F0-12-D8.props
loadProperties: 00-26-32-F0-12-D8.props
bandRestoreState: restore bands
memRestoreState: restore memory
RESTORE: index=0 title=10
RESTORE MEM:Mem 0=FreqA    28010000
RESTORE: index=0 mode=4
RESTORE: index=0 filter=0
RESTORE: index=1 title=10
RESTORE MEM:Mem 1=FreqA    28010000
RESTORE: index=1 mode=4
RESTORE: index=1 filter=0
RESTORE: index=2 title=10
RESTORE MEM:Mem 2=FreqA    28010000
RESTORE: index=2 mode=4
RESTORE: index=2 filter=0
RESTORE: index=3 title=10
RESTORE MEM:Mem 3=FreqA    28010000
RESTORE: index=3 mode=4
RESTORE: index=3 filter=0
RESTORE: index=4 title=10
RESTORE MEM:Mem 4=FreqA    28010000
RESTORE: index=4 mode=4
RESTORE: index=4 filter=0
radio: vfo_init
vfo_init: width=525 height=60
radio: meter_init
meter_init: width=200 height=60
Create 2 receivers: height=150
create_receiver: id=0 buffer_size=4096 fft_size=2048 pixels=800 fps=10
create_receiver: id=0 default adc=0
receiver_restore_state: id=0
create_receiver: id=0 output_samples=2048
create_receiver: id=0 after restore adc=0
create_receiver: OpenChannel id=0 buffer_size=4096 fft_size=2048 sample_rate=96000
create_panel: channel=0 run=1 gain1=4.000000 gain2I=1.000000 gain2Q=1.000000
RXASetNC 2048
RXASetMP 0
SetAnalyzer id=0 buffer_size=4096 overlap=0
receiver: create_visual: id=0 width=800 height=150
receiver: panadapter_init: height=75 y=0
receiver: waterfall_init: height=75 y=75
receiver 0: height=150 y=60
create_receiver: id=1 buffer_size=4096 fft_size=2048 pixels=800 fps=10
create_receiver: id=1 default adc=0
receiver_restore_state: id=1
create_receiver: id=1 output_samples=4096
create_receiver: id=1 after restore adc=0
create_receiver: OpenChannel id=1 buffer_size=4096 fft_size=2048 sample_rate=48000
create_panel: channel=1 run=1 gain1=4.000000 gain2I=1.000000 gain2Q=1.000000
RXASetNC 2048
RXASetMP 0
SetAnalyzer id=1 buffer_size=4096 overlap=3392
receiver: create_visual: id=1 width=800 height=150
receiver: panadapter_init: height=75 y=0
receiver: waterfall_init: height=75 y=75
receiver 1: height=150 y=210
Create transmitter
create_transmitter: id=8 buffer_size=4096 mic_sample_rate=48000 mic_dsp_rate=48000 iq_output_rate=48000 output_samples=4096 fps=10
transmitter: allocate buffers: mic_input_buffer=4096 iq_output_buffer=4096 pixels=800
create_transmitter: OpenChannel id=8 buffer_size=4096 fft_size=2048 sample_rate=48000 dspRate=48000 outputRate=48000
create_txa: 8
create_panel: channel=8 run=1 gain1=1.000000 gain2I=1.000000 gain2Q=1.000000
TXASetNC: 2048
TXASetMP: 0
SetAnalyzer id=8 buffer_size=4096 overlap=3392
transmitter: create_visual: id=8
old_protocol_init
old_protocol starting receive thread: buffer_size=4096 output_buffer_size=0
receive_thread: id=0x150b80
old_protocol_init: prime radio
create sliders
sliders_init: width=800 height=90
old_protocol: receive_thread
  Mercury Software version: 33 (0x21)
  Penelope Software version: 17 (0x11)
FPGA firmware version: 2.1
toolbar_init: width=800 height=30 button_width=100
start save timer
LAUNCHING RIGCTL!!
set cursor
start_radio: vfo 0 band=5 bandstack=0 frequency=14010000 mode=4 filter=6 rit=0 lo=0 offset=0
start_radio: vfo 1 band=5 bandstack=0 frequency=14010000 mode=4 filter=6 rit=0 lo=0 offset=0
full_rx_buffer: id=1 fexchange0: error=-2
RIGCTL: Socket created
RIGCTL: Bind done on port 19092
RIGCTL: Waiting for incoming connections...
RIGCTL: Socket created
RIGCTL: Bind done on port 19090
RIGCTL: Waiting for incoming connections...
RIGCTL: Socket created
RIGCTL: Bind done on port 19091
RIGCTL: Waiting for incoming connections...
full_rx_buffer: id=0 fexchange0: error=-2
full_rx_buffer: id=1 fexchange0: error=-2
full_rx_buffer: id=0 fexchange0: error=-2
full_rx_buffer: id=1 fexchange0: error=-2
full_rx_buffer: id=0 fexchange0: error=-2
full_rx_buffer: id=1 fexchange0: error=-2
full_rx_buffer: id=0 fexchange0: error=-2
full_rx_buffer: id=1 fexchange0: error=-2
...
...**

I also tried to forward the display to my x86 machine, to exclude problems with the 7" display. The same effect there, only the sliders and menus, without waterfall/sprectrum is shown. The error messages are the same.

What can be the reason?

Thanks
73, Marcus, DM6TT

**Comment by g0orx** [comment]
I looks like the board just does not have enough CPU to run the 
software. As I do not have one I am unable to test unless someone likes 
to send me one.  You could try just one receiver to see if can handle that.

-- John g0orx/n6lyt

**Comment by dm6tt** [comment]
Thanks John for your reply.
I tried one receiver, without a better result.
I started the programm with strace and found:

Open connection for the X-Display (here the ssh forward on 6010:
**socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 6
setsockopt(6, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(6, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
connect(6, {sa_family=AF_INET, sin_port=htons(6010), sin_addr=inet_addr("127.0.0.1")}, 16) = 0**

and then very often timeouts reading from that socket:
**writev(6, [{"l\0\v\0\0\0\22\0\20\0\0\0", 12}, {"", 0}, {"MIT-MAGIC-COOKIE-1", 18}, {"\0\0", 2}, {"\274]\222c\216\303+\252\231$?a\207cQ\237", 16}, {"", 0}], 6) = 48
recv(6, 0x71540, 8, 0)                  = -1 EAGAIN (Resource temporarily unavailable)
...**

I just checked the CPU. It seems it runs with a Cortex-A7 with one core. So propably the board is really too slow.

I will go back to my rasperry3.

Thanks

73, Marcus
