### ISSUE TITLE
V1.2  Compile error 

### ISSUE THREAD

**Issue by df5sf** [g0orx/pihpsdr#38]
Hi,
I copied the source code in /home/pi/pihpsdr120
I get the following error after make:
/home/pi/pihpsdr120/about_menu.c:120: undefined reference to 'GetWDSPVersion'

73
Uli
DF5SF

**Comment by g0orx** [comment]
You need to update to the latest WDSP on github.

-- John

**Comment by df5sf** [comment]
Hi John,
many thanks, it is ok now
