### ISSUE TITLE
PiHPSDR Rig control IO Error

### ISSUE THREAD

**Issue by W9JSW** [g0orx/pihpsdr#45]
Running v1.2.3 with daily N0NB hamlib to get rigcontrol working with fldigi. Getting initialization failure in fldigi. To debug I tried the following - 

pi@raspberrypi:~ $ rigctl -l | grep -i hpsdr
   240  OpenHPSDR              PiHPSDR                 20170121        Beta

pi@raspberrypi:~ $ sudo rigctl -m 240 -r localhost:19090 f
rig_open: error = IO error

also tried running pihpsdr under sudo - no joy.

Backed up to v1.2.1 - still fails.

**Comment by g0orx** [comment]
Did you enable the port 19090 in Menu->RIGCTL.  By default the port is not running.

**Comment by W9JSW** [comment]
That did it! Thanks...
