### ISSUE TITLE
S-Meter - needle versus bar-graph

### ISSUE THREAD

**Issue by JoNoci** [g0orx/pihpsdr#78]
An install I did in early October of build date 2019-08-14 showed a normal needle S meter - the build I just loaded, build 2019-10-25, shows a bar graph type S meter. Both build show up as Version 2.0.0.

How do I get back to the needle S meter in the latest builds?
When did it change?

Thank you
Joe
V51JN

**Comment by g0orx** [comment]
The default is the bar graph.  Click on the meter and a popup lets you select the type of meter displayed.  It has been like this for some time now.

-- John

**Comment by JoNoci** [comment]
Thank you John!  Still learning this side...
Regards
Joe
