### ISSUE TITLE
PureSignal on Hermes Lite 2

### ISSUE THREAD

**Issue by rack201** [g0orx/pihpsdr#93]
Hi there

PureSignal does not appear to work with the Hermes Lite 2.  Looks like pihpsdr 2 rc2 is not seeing feedback or not at the right level.

Auto-Attenuate does not seem to adjust attenuation and the correcting indicator stays red, regardless of drive level or attenuation setting.  I am using the ’internal’ feedback option.

When running the two tone test, the console fills with ‘Penelope Software version: ##’ if that’s relevant.

Same setup for PS works in OpenHPSDR PowerSDR, but need to change the SetPk value to 0.23 for the Hermes Lite 2 - have tried this in Pihpsdr with no success.

Regards Chris - AG5RR

**Comment by ra1nb0w** [comment]
Read https://raw.githubusercontent.com/wiki/softerhardware/Hermes-Lite2/docs/dl1ycf_hl2.pdf
And use the dl1ycf code.

**Comment by rack201** [comment]
My bug post was over a year ago.  Christoph provided the revised code in response. All is well.

**Comment by ra1nb0w** [comment]
Therefore, you should close this issue.

**Comment by rack201** [comment]
I was unaware it was ever fixed in the main code, so didn’t close it. It’s closed now.
